import type { TestContent } from "@/lib/test-engine/types"

export const en: TestContent = {
  title: "Emotional Intelligence Test (Ability)",
  tagline: "How well you reason about emotions, not how you rate yourself",
  description:
    "A performance-based EQ test. Instead of asking you to rate yourself, it gives you emotional problems to solve: which emotion a situation produces, and the most effective way to handle it. Adapted from the STEU and STEM, validated ability measures used in psychology research.",
  category: "Emotional intelligence",
  scientificBasis:
    "Two performance subtests from the Mayer–Salovey ability model: the Situational Test of Emotional Understanding (STEU-B, scored by Roseman's appraisal theory) and the Situational Test of Emotion Management (STEM-B, scored by expert-rated effectiveness). These measure emotional reasoning as a skill with right and wrong answers. Self-report 'EQ quizzes', by contrast, mostly capture personality and self-image. The item wording here has been lightly modernized for natural, readable English; the scenarios, answer options, and scoring keys follow the published instruments. STEM-B internal reliability is about .84.",
  disclaimer:
    "This measures how well you reason about emotions, which is different from how you actually behave under pressure. Scores are the percentage you answered well, not a percentile or rank, since there's no normative sample built in. It is a tool for self-insight, not a clinical or hiring assessment. The item wording has been adapted for readability (in both English and Vietnamese), so treat this as an adaptation of the original instruments rather than the verbatim validated test.",
  instructions:
    "For each situation, choose the single best answer. Some ask which emotion a person is most likely to feel; others ask the most effective thing they could do. For the action items, pick the most effective response, not necessarily the nicest one or what you personally would do. Pick the best option even when more than one seems reasonable.",
  resultKicker: "Your emotional-reasoning result",
  scoresTitle: "Your scores",
  scoresHint:
    "Understanding and Managing are the two skills tested; Overall is their average. Each is the percentage you got right (Managing awards partial credit for decent-but-not-best choices). These show how you did on the test, not your rank against other people.",
  scale: { minLabel: "", maxLabel: "" },
  dimensions: {
    understanding: {
      label: "Understanding emotions",
      description:
        "Knowing which emotion a situation produces, and how emotions are caused, blend, and change. The reasoning side of EQ.",
      lowLabel: "Still developing",
      highLabel: "Reads emotions accurately",
    },
    managing: {
      label: "Managing emotions",
      description:
        "Knowing the most effective way to handle an emotional situation in yourself and others, not just the nicest or most obvious move.",
      lowLabel: "Still developing",
      highLabel: "Picks effective strategies",
    },
    overall: {
      label: "Overall emotional reasoning",
      description: "The average of your understanding and managing scores.",
      lowLabel: "Still developing",
      highLabel: "Strong",
    },
  },
  outcomes: {
    developing: {
      name: "Developing",
      tagline: "The emotional-reasoning skills are still coming together",
      summary:
        "On this test you often picked answers that don't quite match how emotions usually work, or strategies that aren't the most effective. That's a skill gap, not a character flaw, and emotional reasoning is learnable.",
      longDescription:
        "Emotional understanding and management are skills, and like any skill they respond to practice. A lower score here usually means a few specific habits: reading situations a bit too quickly, or reaching for the response that feels natural rather than the one that works best. The good news is that these are concrete and trainable. Pay attention to what was actually driving an emotion in each scenario, and to which response solved both the feeling and the underlying problem.",
      strengths: [
        "Willing to take an honest look at a real skill rather than a flattering self-rating",
        "Has the most room to grow, which means quick wins are available",
      ],
      growth: [
        "Before reacting, name what specifically caused the emotion (a loss? a threat? someone's intentions?)",
        "Ask which response handles both the feeling and the underlying problem, not just one",
        "Notice when you're choosing the comfortable option instead of the effective one",
      ],
    },
    capable: {
      name: "Capable",
      tagline: "A solid working grasp of how emotions work",
      summary:
        "You read most situations correctly and tend to pick reasonable strategies. You miss some of the subtler cases, the ones where the obvious emotion or the obvious response isn't quite the right one.",
      longDescription:
        "A capable result means your emotional reasoning is sound in everyday situations. Where points slip away is usually the trickier items: emotions that look similar but come from different appraisals (regret vs. disappointment, anger vs. sadness), or situations where the most effective response means addressing the problem and the feeling at once. Closing that gap is mostly about slowing down on ambiguous cases.",
      strengths: [
        "Reads everyday emotional situations accurately",
        "Generally chooses sensible, workable responses",
        "Has a reliable base to build sharper judgment on",
      ],
      growth: [
        "Watch for look-alike emotions that come from different causes (e.g. regret vs. disappointment)",
        "On hard calls, check whether your response handles the problem as well as the mood",
        "Resist defaulting to avoidance or reassurance when something more direct would work better",
      ],
    },
    strong: {
      name: "Strong",
      tagline: "Sharp, accurate reasoning about emotions",
      summary:
        "You correctly read most situations, including subtle ones, and reliably pick effective ways to handle them. Your emotional reasoning is a genuine strength.",
      longDescription:
        "A strong result means you understand not just what people feel but why, and you tend to choose responses that resolve both the emotion and the situation behind it. You distinguish emotions that look alike, and you favour strategies that actually work over ones that merely feel good. The remaining edge is the hardest, most ambiguous cases, plus turning this reasoning into consistent behaviour when you're genuinely stressed, which no written test can measure.",
      strengths: [
        "Accurately reads subtle and ambiguous emotional situations",
        "Chooses responses that address both the feeling and the problem",
        "Distinguishes closely related emotions by their causes",
      ],
      growth: [
        "Push on the hardest cases where even good answers compete",
        "Focus less on knowing the right move and more on doing it under real pressure",
        "Use the skill to coach others, which also deepens your own",
      ],
    },
    exceptional: {
      name: "Exceptional",
      tagline: "Emotional reasoning at the top end",
      summary:
        "You read emotions and choose effective responses with the kind of accuracy that's uncommon. On this test, very little got past you.",
      longDescription:
        "An exceptional result means you reliably identify the true cause of an emotion and select the response that resolves both feeling and situation, even in subtle cases. One honest caveat worth keeping front of mind: this test measures emotional reasoning, knowing the right answer, which is not the same as consistently acting on it when you're tired, triggered, or invested. The frontier for you isn't knowledge; it's turning that knowledge into behaviour, every time.",
      strengths: [
        "Pinpoints what's really driving an emotion, even in ambiguous cases",
        "Consistently selects the most effective response, not just a good one",
        "Strong raw material for leadership, mediation, and counselling-type roles",
      ],
      growth: [
        "Mind the gap between knowing the effective response and enacting it under stress",
        "Watch for over-relying on analysis where warmth or presence matters more",
        "Help others build the reasoning that comes easily to you",
      ],
    },
  },
  questions: {
    steu1: "Xavier finishes a difficult project on time and under budget. How is he most likely to feel?",
    steu2: "It's looking likely that Denise's company will move her to an office much closer to home — something she's really been wanting. How is she most likely to feel?",
    steu3: "Song discovers that a friend borrowed money from people for “urgent bills,” but actually spent it on far less important things. How is Song most likely to feel?",
    steu4: "Charles is meeting a friend to catch a movie, but the friend turns up so late that they miss it. How is Charles most likely to feel?",
    steu5: "Someone is convinced that another person hurt them on purpose, and there's little that can be done to put it right. How is that person most likely to feel?",
    steu6: "Jim loves spending Saturdays at the park with his kids. This year they've taken up sports on Saturdays and can't go with him anymore. How is Jim most likely to feel?",
    steu7: "Megan is house-hunting. Something happens that leaves her feeling regret. What most likely happened?",
    steu8: "Mary was working at her desk when something took her by surprise. What most likely happened?",
    steu9: "Someone believes another person went out of their way to make something good happen for them. How are they most likely to feel?",
    steu10: "Through their own efforts, a person reaches a goal they'd been aiming for. How are they most likely to feel?",
    steu11: "An unwanted situation eases off or stops altogether. How is the person involved most likely to feel?",
    steu12: "Hasad is trying to set up his new phone. He's always been good at figuring out gadgets, but he just can't get this one to work. How is Hasad most likely to feel?",
    steu13: "Dorian's friend is sick and coughs all over him without turning away or covering his mouth. How is Dorian most likely to feel?",
    steu14: "Quan and his wife are talking about their day when something he hears takes him by surprise. What most likely happened?",
    steu15: "A supervisor who was unpleasant to work for leaves Alfonso's company. How is Alfonso most likely to feel?",
    steu16: "Because of changes outside her control, Sara's role shifts and she no longer gets to do the parts of her job she enjoyed most. How is Sara most likely to feel?",
    steu17: "Leila hasn't been sleeping well lately, and nothing in her life has changed that would explain why. How is Leila most likely to feel?",
    steu18: "Someone believes another person deliberately put a stop to something good in their life — but they feel there's something they can do about it. How are they most likely to feel?",
    steu19: "Matthew has been in his current job for six months. Something happens that leaves him feeling regret. What most likely happened?",
    stem1: "Hana and Connie shared an office for years, but Hana takes a new job and the two gradually lose touch. What would be the most effective thing for Connie to do?",
    stem2: "Manuel is only a few years from retirement when he learns his position is being cut — he'll keep a job, but in a less prestigious role. What would be the most effective thing for Manuel to do?",
    stem3: "Diego starts a new job where he doesn't know anyone, and finds people aren't especially friendly. What would be the most effective thing for Diego to do?",
    stem4: "Andre moves away from where his friends and family live, and finds his friends make less effort to stay in touch than he'd hoped. What would be the most effective thing for Andre to do?",
    stem5: "Clayton has been overseas a long time and comes back to visit family. So much has changed that he feels left out. What would be the most effective thing for Clayton to do?",
    stem6: "Daniel has been offered a prestigious position in another country, far from the family he's close to. He and his wife decide it's worth relocating. What would be the most effective thing for Daniel to do?",
    stem7: "Mei Ling picks up the phone and hears that close relatives are in hospital, critically ill. What would be the most effective thing for Mei Ling to do?",
    stem8: "Shona and her nephew were very close when he was younger, but she hasn't spoken to him in months. She calls, but he can only talk for five minutes. What would be the most effective thing for Shona to do?",
    stem9: "Mina and her sister-in-law usually get along well, and the sister-in-law regularly baby-sits for a small fee. Lately she's also been tidying up and commenting on the mess, which Mina finds insulting. What would be the most effective thing for Mina to do?",
    stem10: "Juno is fairly sure his company is going under and his job is at risk. It's a big company and nothing official has been said. What would be the most effective thing for Juno to do?",
    stem11: "Mallory moves from a small company to a very large one, where there's little personal contact — and she misses it. What would be the most effective thing for Mallory to do?",
    stem12: "A demanding client takes up a lot of Jill's time and then asks to speak to her boss about her performance. Her boss reassures her that everything's fine, but Jill still feels upset. What would be the most effective thing for Jill to do?",
    stem13: "Blair and Flynn always grab a coffee at the end of the work week to chat about what's happening at the company. After Blair's job is moved to another part of the company, he stops coming, and Flynn misses their Friday talks. What would be the most effective thing for Flynn to do?",
    stem14: "Michelle's close friend Dara is moving overseas to live with her partner. They've been good friends for years, and Dara probably won't be coming back. What would be the most effective thing for Michelle to do?",
    stem15: "Hannah's access to essential resources has been held up, and her work is now well behind schedule. Her progress report makes no mention of the resource shortage. What would be the most effective thing for Hannah to do?",
    stem16: "Reece's friend points out that her own young children seem to be developing faster than Reece's — and Reece can see it's true. What would be the most effective thing for Reece to do?",
    stem17: "Jumah works part-time while he studies. His shifts for the week are changed at the last minute, without anyone consulting him. What would be the most effective thing for Jumah to do?",
    stem18: "Julie hasn't seen Kira in ages and has been looking forward to their weekend away. But Kira has changed a lot, and Julie finds she's no longer much fun to be around. What would be the most effective thing for Julie to do?",
  },
  options: {
    steu1: { a: "Surprise", b: "Pride", c: "Relief", d: "Hope", e: "Joy" },
    steu2: { a: "Distress", b: "Joy", c: "Surprise", d: "Hope", e: "Fear" },
    steu3: { a: "Anger", b: "Relief", c: "Contempt", d: "Shame", e: "Disappointment" },
    steu4: { a: "Depressed", b: "Frustrated", c: "Angry", d: "Contemptuous", e: "Distressed" },
    steu5: { a: "Dislike", b: "Rage", c: "Jealousy", d: "Surprise", e: "Anxiety" },
    steu6: { a: "Angry", b: "Sad", c: "Frustrated", d: "Distressed", e: "Ashamed" },
    steu7: {
      a: "She didn't put in an offer on a house she wanted, and now she's scrambling to find out whether it's too late.",
      b: "She stumbled on a house she loved and never expected to find.",
      c: "She couldn't put in an offer on a house she liked because her bank didn't release the funds in time.",
      d: "She held off on making an offer on a house she liked, and now someone else has bought it.",
      e: "She's put in an offer on a house and is waiting to hear whether it's accepted.",
    },
    steu8: {
      a: "A coworker told a silly joke.",
      b: "She was tackling a kind of task she'd never dealt with before.",
      c: "She came across results that were different from what she'd expected.",
      d: "She realized she wouldn't be able to finish her work.",
      e: "She had to do a task that wasn't part of her usual routine.",
    },
    steu9: { a: "Hope", b: "Pride", c: "Gratitude", d: "Surprise", e: "Relief" },
    steu10: { a: "Joy", b: "Hope", c: "Relief", d: "Pride", e: "Surprise" },
    steu11: { a: "Regret", b: "Hope", c: "Joy", d: "Sadness", e: "Relief" },
    steu12: { a: "Distressed", b: "Confused", c: "Surprised", d: "Relieved", e: "Frustrated" },
    steu13: { a: "Anxiety", b: "Dislike", c: "Surprise", d: "Jealousy", e: "Rage" },
    steu14: {
      a: "His wife was talking a lot, which was unusual for her.",
      b: "His wife brought up topics that were different from what they usually discussed.",
      c: "His wife told him she might have some bad news.",
      d: "His wife told him some news that wasn't at all what he'd expected.",
      e: "His wife told a funny story.",
    },
    steu15: { a: "Joy", b: "Hope", c: "Regret", d: "Relief", e: "Sadness" },
    steu16: { a: "Ashamed", b: "Sad", c: "Angry", d: "Distressed", e: "Frustrated" },
    steu17: { a: "Angry", b: "Scared", c: "Sad", d: "Distressed", e: "Guilty" },
    steu18: { a: "Angry", b: "Contemptuous", c: "Distressed", d: "Depressed", e: "Frustrated" },
    steu19: {
      a: "He didn't apply for a job he wanted, and has just learned that someone less qualified got it instead.",
      b: "He didn't apply for a job he wanted, and has started looking for something similar.",
      c: "He found out that chances for promotion have dried up.",
      d: "He found out he didn't get a position he'd expected to get.",
      e: "He never heard about a job he could have applied for, and now it's too late.",
    },
    stem1: {
      a: "Accept that she's gone and the friendship is simply over.",
      b: "Call Hana and ask her out for lunch or coffee to catch up.",
      c: "Reconnect with Hana to catch up, but also get to know her replacement in the office.",
      d: "Spend time getting to know the other people in the office and strike up new friendships.",
    },
    stem2: {
      a: "Think it through carefully and talk it over with his family.",
      b: "Raise it with his boss or management.",
      c: "Accept the situation, but stay bitter about it.",
      d: "Quit on the spot.",
    },
    stem3: {
      a: "Have fun with his own friends outside of work hours.",
      b: "Focus on doing his work well at the new job.",
      c: "Make the effort to talk to people and be friendly himself.",
      d: "Leave and find a job with a better atmosphere.",
    },
    stem4: {
      a: "Settle into the new city by joining clubs and activities there.",
      b: "Make the effort to reach out to them, while also meeting new people where he lives now.",
      c: "Let go of friends who've shown themselves to be unreliable.",
      d: "Tell his friends he's disappointed they haven't been in touch.",
    },
    stem5: {
      a: "Nothing — it'll sort itself out soon enough.",
      b: "Tell his family he feels left out.",
      c: "Spend time listening and getting involved again.",
      d: "Remind himself that relationships naturally change over time.",
    },
    stem6: {
      a: "Decide he shouldn't have applied if he didn't really want to leave.",
      b: "Set up a routine for staying in touch, like weekly calls or video chats.",
      c: "Focus on the great opportunities the move offers.",
      d: "Turn down the position.",
    },
    stem7: {
      a: "Let herself cry and feel it for as long as she needs to.",
      b: "Steady herself by talking to other family to find out what's happening, then go to the hospital.",
      c: "Accept that there's nothing she can do.",
      d: "Go straight to the hospital and ask staff about their condition.",
    },
    stem8: {
      a: "Accept that he's growing up and may not want to spend as much time with family now.",
      b: "Plan to drop by and visit him in person for a proper catch-up.",
      c: "Accept that relationships change, but keep calling him now and then.",
      d: "Feel hurt, but tell herself there's nothing she can do.",
    },
    stem9: {
      a: "Let her sister-in-law know the comments have hurt her.",
      b: "Find a new babysitter.",
      c: "Be grateful her house is getting cleaned for free.",
      d: "Ask her to only baby-sit and leave the cleaning.",
    },
    stem10: {
      a: "Find out what's actually going on and talk through his concerns with his family.",
      b: "Try to keep the company afloat by working harder.",
      c: "Start applying for other jobs.",
      d: "Treat it as a chance for a fresh start.",
    },
    stem11: {
      a: "Talk to her coworkers, build social connections, and make friends.",
      b: "Start looking for a new job so she can leave that environment.",
      c: "Just give it time — things will be okay.",
      d: "Lean on her friends outside work and colleagues from previous jobs.",
    },
    stem12: {
      a: "Vent to her friends or coworkers about it.",
      b: "Ignore the incident and move on to her next task.",
      c: "Calm down by taking some deep breaths or going for a short walk.",
      d: "Remind herself she's had plenty of success before and this client being difficult isn't her fault.",
    },
    stem13: {
      a: "Keep going to the café or socialize with other coworkers.",
      b: "Not worry about it — ignore the change and leave Blair be.",
      c: "Stop talking to Blair altogether.",
      d: "Invite Blair again, maybe suggesting a different time that works.",
    },
    stem14: {
      a: "Put Dara out of her mind.",
      b: "Keep busy by spending time with other friends.",
      c: "Tell herself Dara and her partner will be back before long.",
      d: "Make a point of staying in touch by email, phone, or letters.",
    },
    stem15: {
      a: "Explain the resource shortage to her boss or management.",
      b: "Take it as a lesson to plan further ahead next time.",
      c: "Note the resource shortage in her progress report.",
      d: "Not worry about it.",
    },
    stem16: {
      a: "Talk the issue over with another friend.",
      b: "Angrily confront her friend for saying such a thing.",
      c: "Remind herself that children develop at different rates.",
      d: "Ask a doctor what the normal range of development looks like.",
    },
    stem17: {
      a: "Refuse to work the new shifts.",
      b: "Find out whether there's a reasonable explanation for the change.",
      c: "Tell the manager in charge of shifts that he's not happy about it.",
      d: "Grudgingly accept the change and work the shifts.",
    },
    stem18: {
      a: "Cancel the trip and go home.",
      b: "Decide it's time to give up the friendship and move on.",
      c: "Accept that people change — move on if needed, but hold on to the good memories.",
      d: "Focus on her other, more rewarding friendships.",
    },
  },
}
